# Generated by Django 4.1.11 on 2023-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mycarrotapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="latest_chat",
            field=models.TextField(null=True),
        ),
    ]
