# Generated by Django 4.2.5 on 2023-10-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrotapp', '0002_userinfo_chatroom_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycarrotapp.userinfo'),
        ),
    ]
