# Generated by Django 4.1.11 on 2023-10-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mycarrotapp", "0002_chatroom_latest_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="manner_temp",
            field=models.FloatField(default=36.5, null=True),
        ),
    ]
