# Generated by Django 4.2.5 on 2023-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarrotapp', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='manner_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='region',
            field=models.CharField(null=True),
        ),
    ]
